### ISSUE TITLE
Prop validation and fallbacks

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-app/builder#1214]
When we first add an element to a tree, if it has required props, it could throw an error, which requires reloading the page to go away.

1 fix would be to validate the props before rendering the element and if it doesn't match (e.g. a required prop is not included) - to not render it and/or to display a warning.

![image](https://user-images.githubusercontent.com/57956282/144857897-397db697-4d74-4039-a3e3-37e2ec9e4225.png)

For this to be executed properly we need to first store all/most of the API interfaces

**Comment by mohasarc** [comment]
I just noticed that another way builder can crash is when providing the wrong prop type. For example, providing `boolean` for `component` prop of any MUI atom.

**Comment by webberwang** [comment]
Relates to https://github.com/codelab-ai/builder/issues/1760
