### ISSUE TITLE
Integrate Codemirror for custom code editor

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1582]
There is current PR with the NPM upgrade, but take a screen recording of graphql schema auto-complete to verify that this works.

**Comment by phmngocnghia** [comment]
- Code mirror: https://www.npmjs.com/package/codemirror-graphql
we have a plan to migrate to code mirror, it also has graphql integration

**Comment by webberwang** [comment]
Let's proceed with codemirror-graphql integration

**Comment by phmngocnghia** [comment]
**Plan**
   - create factory to link code mirror -> code mirror (auto field) of code mirror
   - update query graphql field in add/update operation of resource

**Comment by webberwang** [comment]
> **Plan**
> 
> * create factory to link code mirror -> code mirror (auto field) of code mirror
> * update query graphql field in add/update operation of resource

Great sounds good let’s proceed

**Comment by assimhabeek** [comment]
New Changes : 
- Add `eslint` integration for JS/Typescript editors.
- Remove CM5 totally. We used it for Graphql support. 
         - Syntax highlighting - (exists in CM6)
         - Linting. will be available  in the next version of `graphiql`  https://github.com/graphql/graphiql/pull/2620  
         - Autocomplete schema. [WIP]

**Comment by webberwang** [comment]
We could explore this alternative https://www.npmjs.com/package/codemirror-graphql
