### ISSUE TITLE
Layout Panes Discussion

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1614]
@assimhabeek these were just some random thoughts I had, go through them and see if you have anything to add

## Sidebar Navigation (left most)

There's really only 3 contexts within an app,

- Store https://github.com/codelab-ai/web/issues/1612 
- Builder, main builder
- Resources, allows external api integration 

## Explorer Pane (left pane)

- Contains the hierarchical tree-like information 
- Could have 2 tabs, 1 is page tree, 1 is state tree

### Builder

Contains 2 trees here:

1. Element Tree, this represents the actual page
2. Component Trees, this is a list of components that we have

### Store

1. State
2. Actions

### Resource

1. List of resources

## Config Pane (right pane)

- Contains node specific configurations from explorer pane
- Editor fields will have a toggle that opens in a modal

For example, in the builder explorer pane, we could either select an element or a component. The config pane would show different configurations depending on the node type selected within the project tree.

### Component
1. Config

### Element

1. Config
2. Props
3. CSS
4. Prop inspector

## ~~Editor~~ Workflow Pane (bottom pane)

- Previously thought about naming this editor pane for putting editor fields here, but opted for a modal instead.
- Haven't completely figured out this yet, but in uikbakery they have actions here
- This place should show the pipeline of data from api to ui
- A step of functional chaining steps (hence workflow), a place where binding occurs?

**Comment by assimhabeek** [comment]
@webberwang in `uikbakery` their flow is based on chaining actions. they don't have a global state. so the state is passed among a series of actions. but it is not the case for us. Therefore, I believe the idea of workflow is not applicable and it has no benefits for us. 
If we want to monitor the state and UI here is the things we could display : 
- UI with related state/actions (doesn't really help)
- actions with related state variables  (doesn't really help)
- Full overview for the state shape/current values (important)
- Maybe try and move the store page and see if it fits there.

**Comment by assimhabeek** [comment]
After discussion with Webber, we decided the following: 
- Move state and actions CRUD operations on a tab on the bottom pane
- Create a tab on the bottom pane to display the whole state as json
