### ISSUE TITLE
Creating apps not working in staging

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-app/builder#1705]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/57956282/183299330-9f1b17a9-5ec6-46e1-a996-6fac0a4a6c9a.png">

**Comment by webberwang** [comment]
Which url link is this accessing?

**Comment by antonmihaylov** [comment]
https://builder-j5lb550rg-codelabai.vercel.app/api/graphql

The response is 200
<img width="505" alt="image" src="https://user-images.githubusercontent.com/57956282/183370497-8cfa59f9-cafd-4603-8e46-2e8b8249a19b.png">

But I get Forbidden
<img width="500" alt="image" src="https://user-images.githubusercontent.com/57956282/183370550-133ced8d-9ef8-4c3c-b9f2-3a39d46c48b8.png">

**Comment by antonmihaylov** [comment]
Could it be a auth0 permission issue?

**Comment by webberwang** [comment]
I believe the url is not whitelisted, we've moved the site to `https://app.codelab.ai/apps`, but deployment is still incomplete
