### ISSUE TITLE
Drag dropping a component into the children of another component

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#1753]
## Current Behavior
When a component is drag droped into another component's children an error is thrown; basically because the element tree is expecting an element not a component. 

### Three possibilities exist:

1. Prevent a component from being moved into another component's children.
2. when the component is moved, create an element as an instance of the componenet being moved.
3. Delete the component and make its root element be the one placed in the recieving tree.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/186850078-c32aaa7e-027b-471e-ac58-5a069be61aae.mp4

**Comment by webberwang** [comment]
I think option 2 is the most ideal as it promotes the most reusability.

Option 1 is okay in the meantime as well if option 2 is too much work

**Comment by mohasarc** [comment]
Based on my tests on the latest updates on `master` this doesn't appear to be an issue anymore. When dragging a component into another component it is not moved and no error is thrown.

We can still implement option 2 as a feature.

**Comment by webberwang** [comment]
Related #1767
