### ISSUE TITLE
Action Schema Refactor Discussion

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1774]
## Issue

Our current action structure, do we have limitation where code cannot call a an action within the code? Or would code mirror support that. It seems the modeling would get complex if we supported this, that is something uibakery supports though right.

Let’s call it inline action for discussion sake, this would be schema-less since code block is fully string, which isn’t ideal

## Solution

I think the solution around this is an event driven action flow. So 1 function could call 3 other functions this way.
Instead of 1 action calling 3 inline actions. Our granularity would be at the action level.

We would need to introduce a model called Event (with trigger & listener), each Action would connect with an Event. An Action could trigger an Event, or Respond to an event. This event driven architecture will allow greater flexibility when comparing to the ordering based pipeline.

UI wise, we could have an Action Group view, which visually connects all the actions that are wired together using Event.

To have a closer parallel to coding terminology, I think the following rename is needed.
- CustomAction-> LocalFunction
- ResourceAction -> RemoteFunction
- ActionPipeline would be removed in favor of Events

**Comment by assimhabeek** [comment]
- In addition, instead of passing actions to UI handlers such as `onClick` we pass an Event with possibility to override params.
However this doesn't replace inline actions totally. we can't handle conditions and loops this way. we will need an new structure to handle that

**Comment by webberwang** [comment]
Yeah it seems we are basically creating a programming language at the UI layer, we would need a model for https://en.wikipedia.org/wiki/Control_flow

Would inline using code mirror be easier in the end? How do you with uibakery does it?

**Comment by antonmihaylov** [comment]
What's a use case that events support that regular actions can't?

**Comment by webberwang** [comment]
Event is more declarative while calling action directly more imperative, better at scale down the road. Also makes it so we wouldn't have to inline actions.

Would be overkill now but wanted to discuss it
