### ISSUE TITLE
OGM update can't be batched like GraphQL queries

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1804]
Any thoughts on how to optimize this? Would we switch to GraphQL queries instead of OGM in this case?

`atom.repo.ts` `Atom.update` for example takes very long time when performing on production site

**Comment by antonmihaylov** [comment]
I thought OGM is equivalent to the Graphql API, is it not?
I imagine raw cypher would be fastest if it needs to be optimised.
