### ISSUE TITLE
Add pagination to types page using Option 2

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1820]
Add pagination, and brainstorm below.

Our pagination may have issues, even if we set item to 20 max per page, this would limit 20 to each sub type.

We have around 10 different kind of types, so it potentially could load 20 * 10 = 200 items.

We would need to brainstorm some smarter way of pagination.

**Comment by phmngocnghia** [comment]
RFC:

- use directive addionalLabels (https://neo4j.com/docs/graphql-manual/current/type-definitions/database-mapping/#type-definitions-node) to define extra label "Type" for all Type schema
- update CLI import
  - update repo code to insert with the addional label as ogm won't respect directives...
    - get ids of all types 
    - create cypher to add label "TYPE" for them
- create getTypes resolver
   - parameters like other get types query
   
  limit: Int
  offset: Int

  get entities that have "Type" label using cypher
  apply "limit", "offset"

  return {
    ....
  }

**Comment by webberwang** [comment]
That’s a nice idea! let’s finish the current PR’s and we’ll come back to implement this

**Comment by webberwang** [comment]
@antonmihaylov any thoughts on this?

**Comment by antonmihaylov** [comment]
Yeah, that seems like a good solution

**Comment by webberwang** [comment]
The original goal was to reduce TTI so the webpage becomes interactive as soon as possible. We can't query for union/interface at the root level https://github.com/neo4j/graphql/issues/146 so need our own system

# Option 1

We create a custom query & resolver for the types page

![image](https://user-images.githubusercontent.com/26264925/192726259-611ef49a-8612-4fd9-92f6-fa6dd22c97d0.png)

![image](https://user-images.githubusercontent.com/26264925/192726303-513cfd8e-131e-4bc2-a925-a4ac31bd9b60.png)

# Option 2

We load `TypeBase` data initially then render the table with some deferred data loading (like enum types). The table cell will show loading icon for these non-typeBase data, TTI won't be affected.
