### ISSUE TITLE
Drag and Drop into Builder Feature

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1826]
## Description

Currently we can only drag and drop an atom from the right panel into the DOM tree left panel.

Run `yarn cli seed` and follow prompt to import the seed data only. This will add all the interfaces & atoms, which should show up on the right panel on the builder page.

## Use Case

Drag and drop into the page itself is more intuitive.

**Comment by melhamin** [comment]
@webberwang Could you provide some more explanation? I am not sure what exactly we are trying to do here.
