### ISSUE TITLE
Atom props don't show up on the Inspector->Props tab

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#1837]
## Current Behavior

Atom props cannot be seen/set in the Inspector->Props tab. An error is thrown when the props inspector tab is opened.

## Expected Behavior
Atom props should be seen and set in the props inspector tab.

## Steps to Reproduce

https://user-images.githubusercontent.com/48331678/190680012-db43123f-08ac-42d2-affa-9afcdbe7c93a.mov

**Comment by webberwang** [comment]
I noticed this as well, @mohasarc had worked on the prop panel previously for adding the rich text editor. You guys can decide who wants to take this task

**Comment by mohasarc** [comment]
This issue doesn't exist on an older branch I'm working on rn. It has been introduced recently, testing recent commits might make sense.
