### ISSUE TITLE
Designing a system for platform users to access nextjs server side features

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/builder#1875]
NextJs, has two way to protect routes. either using SSR solution by fetching data in `getServerSideProps` or by client side solution `https://nextjs.org/docs/authentication`

### First approach :
 - Create a new model  `Hook` to allow user insert code
   ```
       id
       code :string
       page: Page // which page to apply this hook
       hookType : getServerSideProps | getInitialProps | getStaticPaths | getStaticProps
   ```
 - Inject the code and run it using `eval` inside the correct hook `hookType` (fetching will be hard since we need to use APIs directly without Mobx services as we can't access them

#### main limitation 
   Usually the user will need to access libs such as `Supabase` or  `Auth0` to check for user status this won't be available because we can't expect which params are required to run the code
#### possible solution
   We could force the user to use one of the libs we make available for him by adding `authPrevoider` for `Hook` model and then a provider param will be available for him  

### Second approach : 
Client side authorization could be achieved using actions. but it requires  a lot of boilerplate to implement authorization in addition to flashing content for users until they are authenticated.

**Comment by webberwang** [comment]
I don't think hooks make sense, these are predefined places for user to add code to for each page. We wouldn't actually use a hook within a function.

I think it would go under `Page.preRendering: [PreRenderingType]`, where `PreRenderType` is either an enum or a model of its own if needed

```
export const getServerSideProps = (ctx) => {
 // USER CODE STARTS
  const returnTo = getFullReturnTo(ctx.req);
  return withPageAuthRequired({ returnTo })(ctx);
  // USER CODE ENDS
};
```

**Comment by assimhabeek** [comment]
- I am sorry I miss-use the term `Hook`, Calling it `PreRenderType` is much better not to confuse it with React hooks. However by saying it could be an enum you mean Pre-implimented  code the user will select such as `Auth0` or `Supabase` or whatever. that is much easier to implement, but less Scalable. so having it as model is the correct option

- I said we can inject it but leave the user to decide what shall we inject by selecting  `authProvider`
