### ISSUE TITLE
Inconsistent interface fields table when updating non-primitive field

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#1880]
## Current Behavior

when updating non-primitive field, the field gets replaced with another field.

## Expected Behavior

table should be consistent with the data.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/192887668-2bc1ab7a-0209-4855-a64a-38fd20a7933f.mp4

**Comment by webberwang** [comment]
This https://github.com/codelab-app/builder/pull/1882 may have solved this inadvertently, could you double check again? Seems to be working for me

https://user-images.githubusercontent.com/26264925/193415041-34369c63-c30c-45fe-8712-7aca5a5e1f60.mov

**Comment by mohasarc** [comment]
I've tested again and the problem seem to presist. It seem to happen only when there is another field of a `PrimitiveType`, can you confirm?

**Comment by webberwang** [comment]
Issue I see is that field key's should be unique, I'll update the schema & test

**Comment by mohasarc** [comment]
Seems to have been fixed by #1911
