### ISSUE TITLE
Config pane issues

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#1906]
## Current Behavior
While navigting between tabs, they don't replace each other. Additionally, clicking on Components throws an error. This issue appeared recently so I assume it had happened in the last few commits.
Update: This issue seems to have first appeared in c3d4891227ee85fbe07094e9e1c808c8e07864e8
Update2: It is related to the updating `antd` version

![Screenshot from 2022-10-06 20-55-33](https://user-images.githubusercontent.com/51242349/194386092-4f4db998-04ed-4a09-9a92-255d6540a9d5.png)

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/194386511-7ed1930c-b099-42a3-b7f2-10dba8a49ef7.mp4

**Comment by webberwang** [comment]
Yeah looks like they changed how tabs work, I'll update it to see if it helps
