### ISSUE TITLE
Error after deleting an internal element

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#1915]
## Current Behavior
An error is thrown after deleting the first child of an element. Deleting other children work fine. 

## Steps to Reproduce

https://user-images.githubusercontent.com/48331678/194724165-d01f8940-139e-4075-867a-2708cbbbb2a0.mov

**Comment by mohasarc** [comment]
I've encountered the same issue. It doesn't have to be the first element - deleting any internal element (there is another element linked to it) cause the issue.
