### ISSUE TITLE
Store model context refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1926]
Looking to remove context from our services & models, to make it more explicit.

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/195214912-443e3429-774b-4748-9aee-b73f6661b8a0.jpg)

- [ ] For getting rid of `getActionService`, it make sense to add `Store.actions` as a property so we have access to actions from store.
- [ ] For getting rid of `getTypeService`, we could store a `Store.state` as `Ref<IInterfaceType>`

**Comment by assimhabeek** [comment]
@webberwang 
Rolling back from `Store.actions`. because it won't be updated when an action is created.
