### ISSUE TITLE
Elements disapear sometimes when drag dropped

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#1969]
## Current Behavior

When drap dropping an element into a location between itself and the next element, it disappears. Additionally, the entire page freezes.

## Expected Behavior
No elements should be lost when drag dropped.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/199079318-d15008ce-1169-473e-94e7-e584fd414b48.mp4

**Comment by mohasarc** [comment]
This seems to be making these beautiful shapes in the DB :D, where an element is a `NODE_SIBLING` with itself and the connection to the parent is lost.

![Screenshot from 2022-10-31 21-26-46](https://user-images.githubusercontent.com/51242349/199082372-ef19b88e-ddef-4af1-a190-da3ca2dc45b5.jpg)

**Comment by mohasarc** [comment]
A related issue, quickly dnd elements cause circular `NODE_SIBLING` referances. same issue happen when using the element tree on the left pane.

https://user-images.githubusercontent.com/51242349/199481904-20f69db9-44ac-4d26-bf39-2b74d9156332.mp4

**Comment by melhamin** [comment]
I believe the order of update requests to the db are not persisted when moving the elements around, which leads to this issue.

**Comment by mohasarc** [comment]
Yeah, that is what happened probably.
