### ISSUE TITLE
Error when creating an array type for some types

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#1980]
## Current Behavior
Creating an array with a `String` and `Integer` primitive types fails. However, `Boolean` and `Float` work fine. Also when changing the first letter of the `String` and `Integer` into a small case it works fine.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/200137152-78240279-993a-4278-a38b-8c0e155e57fc.mp4

**Comment by tinhw3** [comment]
This seems we cannot add PrimitiveType if it already exists. Creating an array with a `String` primitive types works. I think we can send a more  friendly error message. Please check the attachment.

https://user-images.githubusercontent.com/117329462/200261527-6b1d7002-aa77-4ca9-bed0-1932232bd2ce.mov

**Comment by webberwang** [comment]
@mohasarc the screen recording shows creation of string as opposed to array of string

**Comment by mohasarc** [comment]
Ahh yeah that's true, my bad.. sorry about that!
