### ISSUE TITLE
"yarn commit" command creates invalid commit message

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#1992]
## Current Behavior

When following the instructions after running "yarn commit" - the command creates a message which does not pass validation, and no commit created.
After entering the issue number it is appended before commit subject:
<img width="598" alt="Снимок экрана 2022-11-09 в 12 35 36" src="https://user-images.githubusercontent.com/74900868/200808123-55b808f6-e9a4-4e69-8cdb-877bbe8b060a.png">
And then commit validation fails with error:
<img width="684" alt="Снимок экрана 2022-11-09 в 12 36 43" src="https://user-images.githubusercontent.com/74900868/200808248-ed9c1725-5ef0-411a-8e76-81b21b91471f.png">

## Expected Behavior

Need to append issue number at the end to avoid error

## Steps to Reproduce

Simply run `yarn commit` and follow instructions

**Comment by webberwang** [comment]
Good catch! I'll fix this

**Comment by webberwang** [comment]
https://github.com/leoforfree/cz-customizable/blob/master/lib/build-commit.js#L75-L79

```typescript
const head =
    addType(answers.type, config) +
    addScope(answers.scope, config) +
    addTicketNumber(answers.ticketNumber, config) +
    addSubject(answers.subject.slice(0, config.subjectLimit));
```

Could fork and move ticket number to end, but too much overhead to maintain, we'll just type out commit message manually (it's faster imo than using `yarn commit`)
