### ISSUE TITLE
Apps are deleted after running the Builder

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#2024]
## Current Behavior

All existing apps are deleted after running `nx serve builder`.

## Steps to Reproduce

https://user-images.githubusercontent.com/48331678/202253898-e875d4bb-271d-458a-bf0b-252e8d0a1b34.mov

**Comment by webberwang** [comment]
wait this seems like a big issue, not sure how it happens

**Comment by webberwang** [comment]
I tried it out and didn't reproduce it, maybe it was already deleted but didn't reflect initially?

Have you tried to create one, restart server, and check if it exists?

**Comment by M-Abozaid** [comment]
Do you `Error: Cannot return null for non-nullable field Page.isProvider.` after reloading?
If so it's likely you have pages missing the new `isProvider` field #1785 which is required.
I think you will need to reset the database or update the old pages.

**Comment by melhamin** [comment]
> Do you see `Error: Cannot return null for non-nullable field Page.isProvider.` after reloading? If so it's likely you have pages missing the new `isProvider` field #1785 which is required. I think you will need to reset the database or update the old pages.

I never got this error. Yeah after resetting the db, I couldn't reproduce it again.
