### ISSUE TITLE
Lost apps

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/builder#2031]
## Current Behavior

Created apps get lost for some reason; although they're available in the DB.

## Screenshots Showing Bug
![Screenshot from 2022-11-18 09-21-33](https://user-images.githubusercontent.com/51242349/202635277-6862ab30-e17e-4c11-8502-40dacbeb23f6.png)
![Screenshot from 2022-11-18 09-21-38](https://user-images.githubusercontent.com/51242349/202635282-2e488c6f-28ff-4f8f-a8e5-5fca0a035c7d.png)

**Comment by webberwang** [comment]
Related to #2024

**Comment by webberwang** [comment]
@mohasarc Related to #2024
