### ISSUE TITLE
Types table pagination issue

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#2050]
## Current Behavior
`count/page` is not respected when the table is filtered by a column.

## Video Showing Bug

https://user-images.githubusercontent.com/48331678/203840109-0b3d864f-ef8b-4dba-837b-56ed48f61d58.mov

**Comment by melhamin** [comment]
@mohasarc related to #2037 ?

**Comment by melhamin** [comment]
@mohasarc related to #2037 ?

**Comment by mohasarc** [comment]
That's an interesting behavior. it is not exactly the same but similar to #2037. I think we need to start doing the filtering on the cloud side @webberwang.

**Comment by mohasarc** [comment]
Actually this issue is directly related to this #1991; They both need server side filtering.
