### ISSUE TITLE
Button title is lost if any other prop changed

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#2055]
## Current Behavior
The text of the button atom (which was successfully saved to DB) is removed when any other prop is edited on Props form.

## Video Showing Bug

https://user-images.githubusercontent.com/74900868/204106510-6558e517-26ec-4049-8fc3-de7caf3e815c.mov

**Comment by jethrocabaluna** [comment]
@webberwang This is duplicated by https://github.com/codelab-app/builder/issues/2110 and was fixed already with https://github.com/codelab-app/builder/pull/2123

[button-title-lost-fixed.webm](https://user-images.githubusercontent.com/27695022/210779228-a0432965-4291-4f09-bed7-b2936982cec4.webm)
