### ISSUE TITLE
Fix browser console errors

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#2057]
## What Feature Can Be Enhanced?
Currently when any of the pages are open - there is plenty of errors displayed.
Some of them are:
- [x] Received `false` for a non-boolean attribute `hide`.
- [x] [antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly. 
- [x] Prop `style` did not match. Server: "height:-350px" Client: "height:619px"
- [x] [antd: Dropdown] `visible` is deprecated which will be removed in next major version, please use `open` instead.
- [x] [antd: Dropdown] `onVisibleChange` is deprecated which will be removed in next major version, please use `onOpenChange` instead. 
- [x] [antd: Modal] `visible` will be removed in next major version, please use `open` instead. 
- [ ] Received `true` for a non-boolean attribute `nullable`.
- [x] Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
- etc?

**Comment by tinhw3** [comment]
@vladyslav-polishchuk Hi, how to reproduce `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`?/
