### ISSUE TITLE
Make pages with paginated tables URL-driven

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#2066]
Pages `tags`, `atoms`, `types` (maybe some other pages as well) display tables with data that support pagination.
It is a good practice to make such pages URL-driven, so that users may refresh/bookmark/share page similar to this:
`http://127.0.0.1:3000/types?page=3&pageSize=25` and always get the same result without a need to setup pagination parameters again

**Comment by webberwang** [comment]
Yes this is a great idea
