### ISSUE TITLE
Atoms are not populated with default values

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#2070]
## Current Behavior
When any atom is added to the builder - all the default values are ignored and the component always renders without any values.
Before reproducing the bug - edit some atom API and add a default value to some field. In my example I added default value to field `maxLength` on `AntDesignInput` atom

## Video Showing Bug

https://user-images.githubusercontent.com/74900868/205371164-e07b80b0-ce76-4015-a18d-6b16e1595846.mov

**Comment by kennethpdev** [comment]
@vladyslav-polishchuk do you know what should be the expected default props? Are they the ones that are set once you make some changes to the props tab?

When I try to set the `maxLength` two other props were being added, the `disabled` and `bordered` properties.

```
{
    "maxLength": 5,
    "disabled": false,
    "bordered": false
}
````

if I revert the `maxLength` to `0`, all these 3 props remain. Are these values should be the expected default props when adding the atom to the builder? Thanks
