### ISSUE TITLE
Display option improvement

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#2082]
## Description

I also missed additional CSS display options when I was creating a demo. And a position prop

<img width="318" alt="Screenshot 2022-12-06 at 11 57 54" src="https://user-images.githubusercontent.com/26264925/205881153-6899a38e-dacb-475e-8248-33d3d09a53da.png">

- [ ] Add position prop for CSS

**Comment by vladyslav-polishchuk** [comment]
Looks like there already exists `position` prop. Did not notice that when created the issue. Looks like only work on extending `display` option should be done
