### ISSUE TITLE
Make page rendering async so that it does not freeze UI

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/builder#2083]
## What Feature Can Be Enhanced?
Currently when any page is opened in (builder mode or not) the UI freezes.
It makes a product much more user-friendly if such operations are not UI-blocking and also has some visual indicator like a spinner

https://user-images.githubusercontent.com/26264925/206812542-6ae54cd9-bb34-4612-8b93-d9026b4a4fbf.mov

**Comment by webberwang** [comment]
Could you add a video to this issue?
