### ISSUE TITLE
Error setting element props

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#2085]
## Video Showing Bug

https://user-images.githubusercontent.com/48331678/206046335-23f61b56-f11f-483c-9f30-2e22f8a927ba.mov

**Comment by vladyslav-polishchuk** [comment]
99% is the same issue as here - [ReactNodeType field type does not work on Props form#2059](https://github.com/codelab-app/builder/issues/2059). Fix is in progress, need to wait and check again
