### ISSUE TITLE
No change when set to 0

### ISSUE THREAD

**Issue by tinhw3** [codelab-app/builder#2099]
## Description

https://user-images.githubusercontent.com/117329462/206643475-56b4411a-d68c-4b7f-8adf-7bb82e19d2e4.mov

**Comment by jethrocabaluna** [comment]
@webberwang The current open PR https://github.com/codelab-app/builder/pull/2130 should fix it already. I think the PR is fine.

[input-number-0.webm](https://user-images.githubusercontent.com/27695022/210769487-1f6cfa73-ace6-41b8-92c5-d89698e04f17.mp4)
