### ISSUE TITLE
Detailed page for a single type

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/builder#2140]
## Description

It would be great to have a page for a single type as it can get more complicated in the future to the point that our nested table on the types pagination can also get too complicated. Also it will be better for opening a type via url query as we can avoid requesting unnecessary data in the pagination page.

We could also have a feature in the future where we can have recently visited pages or favorites and they work great if we have a page for single data like types

In this new page, we should be able to render different Types and do CRUD operations on the Type itself or its sub types (e.g. if it is an interfaceType)

**Comment by mohasarc** [comment]
closing this in favor of a modal-based approach we talked about earlier and detailed in #2153
